# Main Hydra Configuration for GPU NUMA Experiments
# This is the entry point that composes other configurations

defaults:
  - experiment: rq1_model_architecture_impact
  - _self_

# Output configuration
output:
  base_dir: "experiments"
  nsys_reports_dir: "nsys_reports"
  logs_dir: "logs"  
  results_file: "results.json"

# Global overrides (can be overridden from command line)
hydra:
  # Automatic experiment directory creation with timestamps
  run:
    dir: experiments/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  
  # For multi-run parameter sweeps
  sweep:
    dir: experiments/${experiment.name}_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
  
  # Configure logging
  job_logging:
    level: INFO
    handlers:
      file:
        filename: experiment.log